### PR TITLE
Add new series header to old series template header

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Adds our new header from the new series landing page template to the old series page template header in `header-rezone.php`
- Allows the styling for the series header/banner to be used even if the parent container is not `.cftl-tax-landing-template-series-landing-special-projects-php`

Main page:
screencapture-citylimits-test-series-futuremap-2020-02-21-10_49_01

Interior page:
screencapture-citylimits-test-neighborhoods-bay-street-2020-02-21-10_49_49

Mobile:
screencapture-citylimits-test-series-futuremap-2020-02-21-10_49_24

## Why

For #147

## Testing/Questions

Features that this PR affects:

- Old series template header partial

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?
- [ ] Could any of this be done better?
- [ ] Any design flaws that need to be fixed?

Steps to test this PR:

1. View a series landing page using the old template
2. View on frontend and make sure it looks ok

### CODE REVIEW

**Comment by benlk** [comment]
- What can we do to improve the layout for series that do not have a featured image on the landing page? Or is that a concern?
- Are we worried about the red underlines on the menu bits on mobile on /series/futuremap? 
Screen Shot 2020-02-21 at 13 06 05

**Comment by joshdarby** [comment]
> What can we do to improve the layout for series that do not have a featured image on the >landing page? Or is that a concern?
>Are we worried about the red underlines on the menu bits on mobile on /series/futuremap?

I think those are better answered by @MirandaEcho 😄

**Comment by kaylima** [comment]
@benlk how much time would it take to remove the red lines underneath and also remove the white to the left of "News" OR to add a white line to the left of "Get involved" so that it's consistent?

**Comment by joshdarby** [comment]
> how much time would it take to remove the red lines underneath and also remove the white to the left of "News" OR to add a white line to the left of "Get involved" so that it's consistent?

@kaylima About 5 minutes for each issue + time for review

Screen Shot 2020-02-21 at 4 55 29 PM

**Comment by joshdarby** [comment]
Updated in https://github.com/INN/umbrella-citylimits/pull/161/commits/74afb8ab0d02d24038f0a5fded9aa6660f743763

**Pull request merged**
