### PR TITLE
Add a Special Projects template, and format its header

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This pull request makes the following changes:

- adds the series landing page template for special projects
    - supports bylines (not in mockup, but enabled by default in Largo)
    - supports description
    - supports HTML content area (not in mockup, but City Limits has historically used it)
    - supports social media sharing buttons (not in mockup, but enabled by default in Largo)
- does not implement the centered "Special Project" tag from https://user-images.githubusercontent.com/1754187/67224179-a7903780-f3fe-11e9-95d8-2f00e9fa4111.png because that doesn't match how the tag has been styled on the posts widgets in #67's fancy section widgets for the homepage

Screenshot_2019-11-04 Election Watch 2018 City Limits-mobile
Screenshot_2019-11-04 Election Watch 2018 City Limits-tablet
Screenshot_2019-11-04 Election Watch 2018 City Limits

## Why

For #68 and to give us a template for testing special projects widgets as part of #71

## Testing/Questions

Features that this PR affects:

- no existing features

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?
- [ ] should this implement the fancy centered-with-borders styles for the "Special Project" tag?

Steps to test this PR:

1. Create a new series landing page, or edit an existing one.
2. Set the template to Series Landing Page - Special Projects:  
    Screen Shot 2019-11-04 at 15 29 18
3. Set the title and description.
4. Set a featured image for the landing page.
5. Save/Update.
6. View the landing page.

### CODE REVIEW

**Comment by joshdarby** [comment]
@benlk Do you think we should increase the height and padding on the `series-header` element on larger screen sizes so it matches the mockup more closely?

Here's how it looks at 1920px
Screen Shot 2019-11-05 at 12 04 01 PM

**Comment by benlk** [comment]
Part of the apparent-size problem is that the containing element is the minimum size of its content. Putting more words in the description will make the box bigger.

Screen Shot 2019-11-05 at 21 14 57

**Comment by benlk** [comment]
Changes in https://github.com/INN/umbrella-citylimits/pull/88/commits/a94f095cf35c2344013be41dbb2adf14c9dd9d6a:

- on browsers more than 500px tall, the margin-top on the title increases by 50%
- the width of the description drops to 40%, but gains a min-width of 25em so that it won't get squished on smaller viewports.

Screen Shot 2019-11-05 at 21 22 49
Screen Shot 2019-11-05 at 21 23 03
Screen Shot 2019-11-05 at 21 23 12
Screen Shot 2019-11-05 at 21 23 18

**Comment by joshdarby** [comment]
@benlk The changes in https://github.com/INN/umbrella-citylimits/commit/a94f095cf35c2344013be41dbb2adf14c9dd9d6a look good 👍

>  should this implement the fancy centered-with-borders styles for the "Special Project" tag?

I would think so, since that's how the mockup looks for the mobile version.

Screen Shot 2019-11-06 at 9 46 53 AM

**Comment by benlk** [comment]
Pseudoelement hax in https://github.com/INN/umbrella-citylimits/pull/88/commits/e26b24123853d30dc334170c993e4958838c1be2 gets us this without having to add a new border-image in `img/`:
Screen Shot 2019-11-06 at 15 37 05
Screen Shot 2019-11-06 at 15 37 17
Screen Shot 2019-11-06 at 15 37 30

**Pull request merged**
