### PR TITLE
Update Grunt, remove unnecessary items from Gruntfile, register task 'default'

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This pull request makes the following changes:

- Updates grunt dependencies
- Drops `package.lock`
- Removes the `version` task, because we haven't been versioning this software for release
- Drops `grunt-contrib-pot`, `grunt-confirm`, `grunt-git`, `grunt-po2mo`, `grunt-pot`, and `grunt-version` as they're unused in this project. If we end up making this theme translatable, we should use `grunt-shell` as a wrapper for the `wp i18n` tools.

## Why

This should clear up the [npm-related security alerts for this repo](https://github.com/INN/umbrella-citylimits/network/alerts), as well as bring improved syntax handling in LESS files for CSS' `calc()`.

## Testing/Questions

Features that this PR affects:

- CSS/LESS compilation in dev mode

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?

Steps to test this PR:

1. the CSS loads, right?
2. Run `grunt` and watch for errors: there should be none, and the `default` task should be run.

### CODE REVIEW

**Comment by joshdarby** [comment]
@benlk This works fine, but something in either this or the PR that was just merged (#33) is causing the main nav dropdowns to not display.

**Comment by benlk** [comment]
Yep, I'm seeing that with #33 checked out as well. Will put a patch in this PR.

**Comment by joshdarby** [comment]
@benlk Do you want help narrowing down what happened or do you have an idea?

**Comment by benlk** [comment]
Assistance would be welcome.

**Comment by benlk** [comment]
It's not https://github.com/INN/largo/pull/1715/

**Comment by benlk** [comment]
@joshdarby does this go away for you if in Appearance > CSS Variables  you hit "Save Variables"?

**Comment by joshdarby** [comment]
@benlk Sure does.

**Comment by benlk** [comment]
Then it sounds like both of us had pre-Largo-0.6.4 CSS compiled, but since that isn't updated automatically when Largo updates (we require a human to push the button) we had to clear the old styles and generate new ones. It's not a problem with this PR or #33, or even this theme.

(And https://github.com/INN/largo/issues/1137 would solve the problem by getting rid of that cached stylesheet.)

OK to merge?

**Comment by joshdarby** [comment]
Awesome. 👍

**Pull request merged**
