### PR TITLE
Special projects "Latest news" section: 7 posts from the series

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This pull request makes the following changes:

- Takes formerly homepage-specific byline styles for widgets and applies them to widgets sitewide
- Adds a new "Seven Series Posts" widget, with styles based off the mockup and the homepage's Largo Recent Posts widget
    - limited to 7
    - limited by post query of present page

Here's the mockup:

Screen Shot 2019-11-07 at 13 38 55

Screenshots from localhost:
Screen Shot 2019-11-07 at 14 00 08

Screen Shot 2019-11-07 at 13 55 35

## Why

For #70 

## Testing/Questions

Features that this PR affects:

- site-wide: bylines in widgets and excerpts or other paragraphs in widgets
- adds a new widget

Questions that need to be answered before merging:

- [ ] Is this PR targeting the correct branch in this repository?

Steps to test this PR:

1. Add a City Limits Seven Series Posts widget to a widget area on a series landing page
2. Does it look right?

### CODE REVIEW

**Comment by benlk** [comment]
Filing this as a draft until I get it to limit by the series query of the series it's currently loaded on, but other than that it's ready for review.

**Comment by joshdarby** [comment]
@benlk This looks great, but it looks like if the series has < 6 posts it's pulling in the most recent post from the actual site? ("test post" is the title of it in this instance)

Frontend:
Screen Shot 2019-11-07 at 4 13 19 PM

Posts in `Class of 2013` series I'm testing with
Screen Shot 2019-11-07 at 4 13 14 PM

**Comment by joshdarby** [comment]
Also, not sure if this question is relevant to #70 or #73, but should we remove this from `series-landing-special-projects.php` since we're letting widgets handle displaying posts?

https://github.com/INN/umbrella-citylimits/blob/459e41b8fcce0897549970108095fda7e0c22b67/wp-content/themes/citylimits/series-landing-special-projects.php#L133-L189

**Comment by benlk** [comment]
The backfill on the query has been removed.

We should remove it, since this only goes as low as 5: 

Screen Shot 2019-11-07 at 21 01 37

**Comment by benlk** [comment]
> Also, not sure if this question is relevant to #70 or rather #73, but should we remove this from series-landing-special-projects.php since we're letting widgets handle displaying posts?

done in 19d49e5

**Pull request merged**
