### PR TITLE
Special Projects Secondary Nav

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

Branched off of #88 

- Adds a new `Secondary navigation` metabox to the landing page editor
- Displays the chosen secondary navigation on the landing page and as a dropdown on mobile

Desktop:
Screen Shot 2019-11-06 at 4 08 56 PM

Mobile closed:
Screen Shot 2019-11-06 at 4 09 06 PM

Mobile open:
Screen Shot 2019-11-06 at 4 09 11 PM

## Why

For #69

## Testing/Questions

Features that this PR affects:

- Special projects landing pages

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?

Steps to test this PR:

1. Add a secondary navigation menu to a landing page
2. Make sure landing page template is set to special projects template
3. Verify it looks ok on desktop
4. Verify it looks ok + toggles ok on mobile

### CODE REVIEW

**Comment by joshdarby** [comment]
@benlk This one is branched off of your `68-special-projects-template` branch. Would you rather the target branch for this PR be `68-special-projects-template` or `master`? I'm fine with either.

**Comment by benlk** [comment]
With https://github.com/INN/umbrella-citylimits/pull/88 merged, let's use `master`

**Comment by benlk** [comment]
Are we worried about menu items with long names?
Screen Shot 2019-11-06 at 19 02 29
Screen Shot 2019-11-06 at 19 02 37
Screen Shot 2019-11-06 at 19 02 48

**Comment by joshdarby** [comment]
> Are we worried about menu items with long names?

@benlk Probably. https://github.com/INN/umbrella-citylimits/pull/97/commits/afbd635e877d984de127339f1c28d9d4a14fc802 removes the hardcoded menu height and stops the names from being cut off

Screen Shot 2019-11-07 at 11 30 43 AM

**Comment by benlk** [comment]
Screen Shot 2019-11-07 at 14 56 04
Screen Shot 2019-11-07 at 14 56 32


In the admittedly-peculiar case of a four-line title, should we keep some padding on the list item or anchor? The title of this menu item is `Special Election Voters’ Guide: <br>The Race for Public Advocate`

Or is that too much of an edge case?

**Comment by benlk** [comment]
Miranda's comment in Slack:

> Based on that list from Jarrett that I posted earlier, I don't think we need to worry about four line items
> 
> in any case, can't they change the display text for a menu item to avoid long ones if needed?
> 
> In which case this is an edge situation I don't think we need to worry about

**Pull request merged**
